---
- name: Linux configuration
  hosts: localhost
  connection: local
  become: false

  vars:
    enable_ssh_config: true

  pre_tasks:
    - name: End play if not Linux
      ansible.builtin.meta: end_play
      when: ansible_facts['os_family'] == 'Darwin'

  tasks:
    - name: SSH config
      ansible.builtin.include_tasks: tasks/common/ssh-config.yml
